name: neobank
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.12.0
  lucide_icons: ^0.257.0

  image_picker: ^1.1.0
  signature: ^6.1.0

  flutter_svg: ^2.0.9
  
  # State Management & Storage
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  
  # Utilities
  #image_picker: ^1.1.0  
  #signature: ^6.1.0  

  intl: ^0.20.2
  camera: ^0.10.5

  camera_camera: ^3.0.0
#signature: ^6.3.0
#image_picker: ^1.1.2
  image_cropper: ^11.0.0
  crypto: ^3.0.3
  http: ^1.2.2
  email_validator: ^3.0.0
  pin_code_fields: ^8.0.1
#font_awesome_flutter: ^10.7.0
  video_player: ^2.9.2





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:

    #- assets/neo.png
    - assets/logo.png

    - assets/fd-banner.png
    - assets/neobank_logo.png
   

    - assets/neobank-white.png
    - assets/Card1.png
    - assets/Card2.png
    
    
   # - assets/logo2.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package



    - assets/logo.png

